server:
  port: 10084
spring:
  application:
    name: order-service
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
    import: classpath:application-common-dev.yml
---
spring:
  config:
    activate:
      on-profile: prod
    import: classpath:application-common-prod.yml