server:
  port: 10084
spring:
  application:
    name: order-service
  profiles:
    active: dev
dubbo:
  application:
    name: order-service
  protocol:
    port: 20084
---
spring:
  config:
    activate:
      on-profile: dev
    import: 
      # - optional:classpath:/config/application-common-${spring.profiles.active}.yml
      - optional:classpath:application-common.yml
      - optional:classpath:application-common-dev.yml
---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-common-prod.yml