server:
  port: 10086

spring:
  application:
    name: payment-service
  profiles:
    active: dev

# 支付配置
payment:
  # 法币支付渠道配置
  fiat:
    # 支付宝配置
    alipay:
      app-id: your_alipay_app_id
      private-key: your_alipay_private_key
      public-key: your_alipay_public_key
      gateway-url: https://openapi.alipay.com/gateway.do
      
    # 微信支付配置
    wechat:
      app-id: your_wechat_app_id
      mch-id: your_wechat_mch_id
      api-key: your_wechat_api_key
      cert-path: /path/to/wechat/cert.p12
      
    # 银行转账配置
    bank:
      enabled: true
      timeout-minutes: 30
      
  # 数字资产配置
  crypto:
    # 支持的币种
    supported-currencies:
      - BTC
      - ETH
      - USDT
      - USDC
      
    # 钱包配置
    wallet:
      # 热钱包地址
      hot-wallet:
        btc: your_btc_hot_wallet_address
        eth: your_eth_hot_wallet_address
        usdt: your_usdt_hot_wallet_address
        
      # 冷钱包地址
      cold-wallet:
        btc: your_btc_cold_wallet_address
        eth: your_eth_cold_wallet_address
        usdt: your_usdt_cold_wallet_address
        
  # 价格引擎配置
  price-engine:
    # 价格源配置
    sources:
      - name: binance
        url: https://api.binance.com/api/v3/ticker/price
        weight: 0.4
      - name: coinbase
        url: https://api.coinbase.com/v2/prices
        weight: 0.3
      - name: okx
        url: https://www.okx.com/api/v5/market/ticker
        weight: 0.3
        
    # 价格更新频率（秒）
    update-interval: 5
    
  # 风控配置
  risk-control:
    # 单笔限额
    single-limit:
      usd: 10000
      cny: 70000
      eur: 9000
      
    # 日限额
    daily-limit:
      usd: 50000
      cny: 350000
      eur: 45000
      
    # 滑点控制
    slippage:
      max-percentage: 2.0
      
  # KYC配置
  kyc:
    # KYC级别配置
    levels:
      l0:
        name: "基础验证"
        limit: 1000
      l1:
        name: "身份验证"
        limit: 10000
      l2:
        name: "高级验证"
        limit: 100000
      l3:
        name: "企业验证"
        limit: 1000000
---
spring:
  config:
    activate:
      on-profile: dev
    import: 
      # - optional:classpath:/config/application-common-${spring.profiles.active}.yml
      - optional:classpath:application-common.yml
      - optional:classpath:application-common-dev.yml
---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-common-prod.yml