seed-data:
  super-admin-role-id: 3001
  default-admin-id: 1
  resource:
    start-id: 101
    end-id: 410
  menu:
    start-id: 2001
    end-id: 2042

default-admin:
  username: admin
  password: "123456"
  nickname: 超级管理员

server:
  port: 10083
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,threaddump,heapdump,env
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
spring:
  application:
    name: user-service
  profiles:
    active: dev
dubbo:
  application:
    name: user-service
  protocol:
    port: 20083
---
spring:
  config:
    activate:
      on-profile: dev
    import: 
      # - optional:classpath:/config/application-common-${spring.profiles.active}.yml
      - optional:classpath:application-common.yml
      - optional:classpath:application-common-dev.yml
---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-common-prod.yml
