server:
  port: 10085
spring:
  application:
    name: message-service
  profiles:
    active: dev
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:25}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:false}
          starttls:
            enable: ${MAIL_STARTTLS:false}
dubbo:
  application:
    name: message-service
  protocol:
    port: 20085
---
spring:
  config:
    activate:
      on-profile: dev
    import: 
      # - optional:classpath:/config/application-common-${spring.profiles.active}.yml
      - optional:classpath:application-common.yml
      - optional:classpath:application-common-dev.yml
---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-common-prod.yml