apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: meta-web-three
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mysql
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: meta-web-three
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/redis
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: product-data-pv
  namespace: meta-web-three
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/server/product
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-data-pv
  namespace: meta-web-three
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/server/user
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: order-data-pv
  namespace: meta-web-three
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/server/order
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: message-data-pv
  namespace: meta-web-three
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/server/message
  storageClassName: local-storage
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  namespace: meta-web-three
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer 