-- HRM Department Table
CREATE TABLE IF NOT EXISTS hrm_department (
    id BIGINT NOT NULL COMMENT 'Primary Key',
    code VARCHAR(50) NOT NULL COMMENT 'Department Code',
    name VARCHAR(100) NOT NULL COMMENT 'Department Name',
    parent_id BIGINT DEFAULT 0 COMMENT 'Parent Department ID',
    level INT DEFAULT 1 COMMENT 'Department Level',
    sort_order INT DEFAULT 0 COMMENT 'Sort Order',
    leader_id BIGINT COMMENT 'Department Leader ID',
    status INT DEFAULT 1 COMMENT 'Status: 0-Disabled 1-Enabled',
    remark VARCHAR(500) COMMENT 'Remark',
    tenant_id BIGINT COMMENT 'Tenant ID',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
    deleted INT DEFAULT 0 COMMENT 'Deleted Flag',
    PRIMARY KEY (id),
    UNIQUE KEY uk_code (code, tenant_id, deleted),
    KEY idx_parent_id (parent_id),
    KEY idx_level (level)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Department Table';

-- HRM Position Table
CREATE TABLE IF NOT EXISTS hrm_position (
    id BIGINT NOT NULL COMMENT 'Primary Key',
    code VARCHAR(50) NOT NULL COMMENT 'Position Code',
    name VARCHAR(100) NOT NULL COMMENT 'Position Name',
    department_id BIGINT NOT NULL COMMENT 'Department ID',
    level INT DEFAULT 1 COMMENT 'Position Level',
    base_salary DECIMAL(10,2) DEFAULT 0 COMMENT 'Base Salary',
    status INT DEFAULT 1 COMMENT 'Status: 0-Disabled 1-Enabled',
    description VARCHAR(500) COMMENT 'Job Description',
    requirements VARCHAR(500) COMMENT 'Job Requirements',
    tenant_id BIGINT COMMENT 'Tenant ID',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
    deleted INT DEFAULT 0 COMMENT 'Deleted Flag',
    PRIMARY KEY (id),
    UNIQUE KEY uk_code (code, tenant_id, deleted),
    KEY idx_department_id (department_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Position Table';

-- HRM Employee Table
CREATE TABLE IF NOT EXISTS hrm_employee (
    id BIGINT NOT NULL COMMENT 'Primary Key',
    employee_no VARCHAR(50) NOT NULL COMMENT 'Employee Number',
    name VARCHAR(50) NOT NULL COMMENT 'Employee Name',
    gender INT DEFAULT 1 COMMENT 'Gender: 0-Female 1-Male',
    mobile VARCHAR(20) COMMENT 'Mobile Number',
    email VARCHAR(100) COMMENT 'Email',
    id_card VARCHAR(18) COMMENT 'ID Card Number',
    birthday DATE COMMENT 'Birthday',
    native_place VARCHAR(100) COMMENT 'Native Place',
    nation VARCHAR(50) COMMENT 'Nation',
    marital_status INT COMMENT 'Marital Status: 0-Single 1-Married 2-Divorced',
    political_status VARCHAR(50) COMMENT 'Political Status',
    education INT COMMENT 'Education Level: 0-Junior High and Below 1-High School 2-Technical Secondary 3-College 4-Bachelor 5-Master 6-Doctor',
    graduate_school VARCHAR(100) COMMENT 'Graduate School',
    major VARCHAR(100) COMMENT 'Major',
    hire_date DATE COMMENT 'Hire Date',
    formal_date DATE COMMENT 'Formal Date',
    department_id BIGINT COMMENT 'Department ID',
    position_id BIGINT COMMENT 'Position ID',
    work_location VARCHAR(100) COMMENT 'Work Location',
    status INT DEFAULT 0 COMMENT 'Status: 0-Probation 1-Formal 2-Resigned 3-Leave Without Pay',
    contract_start_date DATE COMMENT 'Contract Start Date',
    contract_end_date DATE COMMENT 'Contract End Date',
    emergency_contact VARCHAR(50) COMMENT 'Emergency Contact',
    emergency_phone VARCHAR(20) COMMENT 'Emergency Contact Phone',
    bank_account VARCHAR(50) COMMENT 'Bank Account',
    bank_name VARCHAR(100) COMMENT 'Bank Name',
    social_security_no VARCHAR(50) COMMENT 'Social Security Number',
    housing_fund_no VARCHAR(50) COMMENT 'Housing Fund Number',
    photo_url VARCHAR(500) COMMENT 'Photo URL',
    remark VARCHAR(500) COMMENT 'Remark',
    tenant_id BIGINT COMMENT 'Tenant ID',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
    deleted INT DEFAULT 0 COMMENT 'Deleted Flag',
    PRIMARY KEY (id),
    UNIQUE KEY uk_employee_no (employee_no, tenant_id, deleted),
    KEY idx_department_id (department_id),
    KEY idx_position_id (position_id),
    KEY idx_status (status),
    KEY idx_mobile (mobile),
    KEY idx_id_card (id_card)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Employee Table';