spring:
  datasource:
    url: jdbc:postgresql://192.168.1.194:5432/metawebthree?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: 123123
  data:
    redis:
      host: 192.168.1.194
      password: 123123
  quartz:
    jdbc:
      initialize-schema: always

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    com.metawebthree: DEBUG
    org.springframework.web: INFO
