spring:
  cloud:
    zookeeper:
      connect-string: 192.168.1.194:2181
  datasource:
    url: jdbc:mysql://172.29.222.103:3306/metawebthree?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
# rocketMQ
rocketmq:
  client:
    namesrv: 192.168.1.194:9876
dubbo:
  registry:
    address: zookeeper://192.168.1.194:2181