spring:
  cloud:
    zookeeper:
      connect-string: localhost:2181
  datasource:
    url: jdbc:mysql://172.29.222.103:3306/metawebthree?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123123
# rocketMQ
rocketmq:
  client:
    namesrv: 192.168.1.194:9876
dubbo:
  registry:
    address: zookeeper://localhost:2181