spring:
  cloud:
    zookeeper:
      connect-string: ${env-ip}:2181
      discovery:
        root: /dev/metawebthree
  datasource:
    url: jdbc:postgresql://postgres-service:5432/metawebthree?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: 123123
# rocketMQ
rocketmq:
  client:
    namesrv: ${env-ip}:9876
dubbo:
  registry:
    address: ${spring.cloud.zookeeper.connect-string}
    protocol: zookeeper
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: -1
# swagger docs
springdoc:
  #   api-docs:
  #     enabled: true
  swagger-ui:
    enabled: true
