spring:
  cloud:
    zookeeper:
      connect-string: ${env-ip}:2181
      discovery:
        root: /dev/metawebthree
  datasource:
    url: jdbc:postgresql://192.168.1.194:5432/metawebthree?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: 123123
  quartz:
    jdbc:
      initialize-schema: always # auto init database tables
dubbo:
  registry:
    address: ${spring.cloud.zookeeper.connect-string}
  application:
    name: ${spring.application.name}
# swagger docs
springdoc:
  #   api-docs:
  #     enabled: true
  swagger-ui:
    enabled: true
# Test configuration for Mockito
mockito:
  inline:
    enabled: false
