x-java-service: &java-service
  environment:
    - SPRING_PROFILES_ACTIVE=dev
    - SPRING_CLOUD_ZOOKEEPER_CONNECT_STRING=zookeeper:2181
  depends_on:
    zookeeper:
      condition: service_healthy
    postgres:
      condition: service_healthy
    redis:
      condition: service_healthy
  networks:
    - meta-web-three
    - default
  restart: unless-stopped

services:
  gateway:
    build:
      context: .
      dockerfile: server/Dockerfile
      target: gateway
    container_name: meta-web-three-gateway
    hostname: gateway
    ports:
      - "10081:10081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_ZOOKEEPER_CONNECT_STRING=zookeeper:2181
    volumes:
      - gateway_data:/server/gateway
      - ./.aws:/.aws:ro
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - meta-web-three
      - default
    restart: unless-stopped
  product-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: product-service
    container_name: meta-web-three-product-service
    hostname: product-service
    ports:
      - "10082:10082"
    volumes:
      - product_service_data:/server/product
      - ./.aws:/.aws:ro
  user-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: user-service
    container_name: meta-web-three-user-service
    hostname: user-service
    ports:
      - "10083:10083"
    volumes:
      - user_service_data:/server/user
      - ./.aws:/.aws:ro
  order-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: order-service
    container_name: meta-web-three-order-service
    hostname: order-service
    ports:
      - "10084:10084"
    volumes:
      - order_service_data:/server/order
      - ./.aws:/.aws:ro
  message-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: message-service
    container_name: meta-web-three-message-service
    hostname: message-service
    ports:
      - "10085:10085"
    volumes:
      - message_service_data:/server/message
      - ./.aws:/.aws:ro
  payment-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: payment-service
    container_name: meta-web-three-payment-service
    hostname: payment-service
    ports:
      - "10086:10086"
    volumes:
      - payment_service_data:/server/payment
      - ./.aws:/.aws:ro
  media-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: media-service
    container_name: meta-web-three-media-service
    hostname: media-service
    ports:
      - "10087:10087"
    volumes:
      - media_service_data:/server/media
      - ./.aws:/.aws:ro
  commission-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: commission-service
    container_name: meta-web-three-commission-service
    hostname: commission-service
    ports:
      - "10088:10088"
    volumes:
      - commission_service_data:/server/commission
      - ./.aws:/.aws:ro
  cart-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: cart-service
    container_name: meta-web-three-cart-service
    hostname: cart-service
    ports:
      - "10089:10089"
    volumes:
      - cart_service_data:/server/cart
      - ./.aws:/.aws:ro
  promotion-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: promotion-service
    container_name: meta-web-three-promotion-service
    hostname: promotion-service
    ports:
      - "10090:10090"
    volumes:
      - promotion_service_data:/server/promotion
      - ./.aws:/.aws:ro
  after-sale-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: after-sale-service
    container_name: meta-web-three-after-sale-service
    hostname: after-sale-service
    ports:
      - "10093:10093"
    volumes:
      - after-sale_service_data:/server/after-sale
      - ./.aws:/.aws:ro
  group-buying-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: group-buying-service
    container_name: meta-web-three-group-buying-service
    hostname: group-buying-service
    ports:
      - "10094:10094"
    volumes:
      - group-buying_service_data:/server/group-buying
      - ./.aws:/.aws:ro
  live-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: live-service
    container_name: meta-web-three-live-service
    hostname: live-service
    ports:
      - "10095:10095"
    volumes:
      - live_service_data:/server/live
      - ./.aws:/.aws:ro
  mall-supplier-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: mall-supplier-service
    container_name: meta-web-three-mall-supplier-service
    hostname: mall-supplier-service
    ports:
      - "10096:10096"
    volumes:
      - mall-supplier_service_data:/server/mall-supplier
      - ./.aws:/.aws:ro
  review-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: review-service
    container_name: meta-web-three-review-service
    hostname: review-service
    ports:
      - "10097:10097"
    volumes:
      - review_service_data:/server/review
      - ./.aws:/.aws:ro
  risk-control-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: risk-control-service
    container_name: meta-web-three-risk-control-service
    hostname: risk-control-service
    ports:
      - "10098:10098"
    volumes:
      - risk-control_service_data:/server/risk-control
      - ./.aws:/.aws:ro
  user-action-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: user-action-service
    container_name: meta-web-three-user-action-service
    hostname: user-action-service
    ports:
      - "10091:10091"
    volumes:
      - user-action_service_data:/server/user-action
      - ./.aws:/.aws:ro
  cs-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: cs-service
    container_name: meta-web-three-cs-service
    hostname: cs-service
    ports:
      - "10092:10092"
    volumes:
      - cs_service_data:/server/cs
      - ./.aws:/.aws:ro
  data-analysis-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: data-analysis-service
    container_name: meta-web-three-data-analysis-service
    hostname: data-analysis-service
    ports:
      - "10099:10099"
    volumes:
      - data-analysis_service_data:/server/data-analysis
      - ./.aws:/.aws:ro
  social-commerce-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: social-commerce-service
    container_name: meta-web-three-social-commerce-service
    hostname: social-commerce-service
    ports:
      - "10100:10100"
    volumes:
      - social-commerce_service_data:/server/social-commerce
      - ./.aws:/.aws:ro
  developer-portal-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: developer-portal-service
    container_name: meta-web-three-developer-portal-service
    hostname: developer-portal-service
    ports:
      - "10115:10115"
    volumes:
      - developer-portal_service_data:/server/developer-portal
      - ./.aws:/.aws:ro
  mes-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: mes-service
    container_name: meta-web-three-mes-service
    hostname: mes-service
    ports:
      - "10101:10101"
    volumes:
      - mes_service_data:/server/mes
      - ./.aws:/.aws:ro
  digital-twin-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: digital-twin-service
    container_name: meta-web-three-digital-twin-service
    hostname: digital-twin-service
    ports:
      - "10102:10102"
    volumes:
      - digital-twin_service_data:/server/digital-twin
      - ./.aws:/.aws:ro
  production-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: production-service
    container_name: meta-web-three-production-service
    hostname: production-service
    ports:
      - "10116:10116"
    volumes:
      - production_service_data:/server/production
      - ./.aws:/.aws:ro
  forecasting-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: forecasting-service
    container_name: meta-web-three-forecasting-service
    hostname: forecasting-service
    ports:
      - "10103:10103"
    volumes:
      - forecasting_service_data:/server/forecasting
      - ./.aws:/.aws:ro
  recommendation-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: recommendation-service
    container_name: meta-web-three-recommendation-service
    hostname: recommendation-service
    ports:
      - "10104:10104"
    volumes:
      - recommendation_service_data:/server/recommendation
      - ./.aws:/.aws:ro
  route-optimizer:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: route-optimizer
    container_name: meta-web-three-route-optimizer
    hostname: route-optimizer
    ports:
      - "10117:10117"
    volumes:
      - route-optimizer_service_data:/server/route-optimizer
      - ./.aws:/.aws:ro
  inventory-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: inventory-service
    container_name: meta-web-three-inventory-service
    hostname: inventory-service
    ports:
      - "10105:10105"
    volumes:
      - inventory_service_data:/server/inventory
      - ./.aws:/.aws:ro
  warehouse-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: warehouse-service
    container_name: meta-web-three-warehouse-service
    hostname: warehouse-service
    ports:
      - "10106:10106"
    volumes:
      - warehouse_service_data:/server/warehouse
      - ./.aws:/.aws:ro
  logistics-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: logistics-service
    container_name: meta-web-three-logistics-service
    hostname: logistics-service
    ports:
      - "10107:10107"
    volumes:
      - logistics_service_data:/server/logistics
      - ./.aws:/.aws:ro
  procurement-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: procurement-service
    container_name: meta-web-three-procurement-service
    hostname: procurement-service
    ports:
      - "10108:10108"
    volumes:
      - procurement_service_data:/server/procurement
      - ./.aws:/.aws:ro
  supplier-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: supplier-service
    container_name: meta-web-three-supplier-service
    hostname: supplier-service
    ports:
      - "10109:10109"
    volumes:
      - supplier_service_data:/server/supplier
      - ./.aws:/.aws:ro
  inventory-alert-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: inventory-alert-service
    container_name: meta-web-three-inventory-alert-service
    hostname: inventory-alert-service
    ports:
      - "10121:10121"
    volumes:
      - inventory-alert_service_data:/server/inventory-alert
      - ./.aws:/.aws:ro
  finance-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: finance-service
    container_name: meta-web-three-finance-service
    hostname: finance-service
    ports:
      - "10110:10110"
    volumes:
      - finance_service_data:/server/finance
      - ./.aws:/.aws:ro
  invoice-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: invoice-service
    container_name: meta-web-three-invoice-service
    hostname: invoice-service
    ports:
      - "10111:10111"
    volumes:
      - invoice_service_data:/server/invoice
      - ./.aws:/.aws:ro
  reporting-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: reporting-service
    container_name: meta-web-three-reporting-service
    hostname: reporting-service
    ports:
      - "10112:10112"
    volumes:
      - reporting_service_data:/server/reporting
      - ./.aws:/.aws:ro
  settlement-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: settlement-service
    container_name: meta-web-three-settlement-service
    hostname: settlement-service
    ports:
      - "10113:10113"
    volumes:
      - settlement_service_data:/server/settlement
      - ./.aws:/.aws:ro
  hrm-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: hrm-service
    container_name: meta-web-three-hrm-service
    hostname: hrm-service
    ports:
      - "10119:10119"
    volumes:
      - hrm_service_data:/server/hrm
      - ./.aws:/.aws:ro
  project-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: project-service
    container_name: meta-web-three-project-service
    hostname: project-service
    ports:
      - "10120:10120"
    volumes:
      - project_service_data:/server/project
      - ./.aws:/.aws:ro
  wallet-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: wallet-service
    container_name: meta-web-three-wallet-service
    hostname: wallet-service
    ports:
      - "10114:10114"
    volumes:
      - wallet_service_data:/server/wallet
      - ./.aws:/.aws:ro
  traceability-service:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: traceability-service
    container_name: meta-web-three-traceability-service
    hostname: traceability-service
    ports:
      - "10118:10118"
    volumes:
      - traceability_service_data:/server/traceability
      - ./.aws:/.aws:ro
  data-pipeline:
    <<: *java-service
    build:
      context: .
      dockerfile: server/Dockerfile
      target: data-pipeline
    container_name: meta-web-three-data-pipeline
    hostname: data-pipeline
    ports:
      - "10122:10122"
    volumes:
      - data_pipeline_data:/server/data-pipeline
      - ./.aws:/.aws:ro

volumes:
  gateway_data:
  product_service_data:
  user_service_data:
  order_service_data:
  message_service_data:
  payment_service_data:
  media_service_data:
  commission_service_data:
  cart_service_data:
  promotion_service_data:
  user-action_service_data:
  cs_service_data:
  after-sale_service_data:
  group-buying_service_data:
  live_service_data:
  mall-supplier_service_data:
  review_service_data:
  risk-control_service_data:
  data-analysis_service_data:
  social-commerce_service_data:
  developer-portal_service_data:
  mes_service_data:
  digital-twin_service_data:
  production_service_data:
  forecasting_service_data:
  recommendation_service_data:
  route-optimizer_service_data:
  inventory_service_data:
  warehouse_service_data:
  logistics_service_data:
  procurement_service_data:
  supplier_service_data:
  inventory-alert_service_data:
  finance_service_data:
  invoice_service_data:
  reporting_service_data:
  settlement_service_data:
  hrm_service_data:
  project_service_data:
  wallet_service_data:
  traceability_service_data:
  data_pipeline_data:
