version: '2'

include:
  - ./docker-compose.dataenv.yml
  - ./server/docker-compose.server.yml

services:
  client:
    build:
      context: "./client"
      dockerfile: dockerfile
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    networks:
      - meta-web-three
networks:
  meta-web-three:
    driver: bridge
