version: '2'
services:
  meta-web-three-mysql:
    image: "mysql"
    restart: always
    volumes:
      - ${DATA_PATH}/.data/mysql:/var/lib/mysql
    #    expose:
    #      - "3306"
    ports:
      - "3306:3306"
    env_file:
      - .env
      - ./gateway/.env
    environment:
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=${TIMEZONE}
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --sql_mode=IGNORE_SPACE,NO_ENGINE_SUBSTITUTION
      --lower_case_table_names=2
    networks:
      - meta-web-three
  meta-web-three-redis:
    image: 'redis:alpine'
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env
      - gateway/.env
    volumes:
      - ${DATA_PATH}/.data/redis:/data
    networks:
      - meta-web-three
  meta-web-three-gateway:
    build:
      context: "./gateway"
      dockerfile: dockerfile
    image: meta-web-three-gateway
    volumes:
      - ${DATA_PATH}/.data/gateway:/gateway
    ports:
      - "30001:30001"
    links:
      - meta-web-three-mysql
      - meta-web-three-redis
    depends_on:
      - meta-web-three-mysql
      - meta-web-three-redis
    networks:
      - meta-web-three
  meta-web-three-server:
    build:
      context: "./server"
      dockerfile: dockerfile
    volumes:
      - ${DATA_PATH}/.data/server:/
    ports:
      - "10082:10082"
      - "10083:10083"
    networks:
      - meta-web-three
    depends_on:
      - meta-web-three-mysql
      - meta-web-three-redis
  meta-web-three-client:
    build:
      context: "./client"
      dockerfile: dockerfile
    ports:
      - "30001:80"
networks:
  meta-web-three:
    driver: bridge
