version: '2'
services:
  mysql:
    image: ${MYSQL_IMAGE}
    restart: always
    volumes:
      - ${DATA_PATH}/.data/mysql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    env_file:
      - .env
      - ./gateway/.env
    environment:
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=${TIMEZONE}
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --sql_mode=IGNORE_SPACE,NO_ENGINE_SUBSTITUTION
      --lower_case_table_names=2
    networks:
      - meta-web-three
  redis:
    image: ${REDIS_IMAGE}
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    env_file:
      - .env
      - gateway/.env
    volumes:
      - ${DATA_PATH}/.data/redis:/data
    networks:
      - meta-web-three
  gateway:
    build:
      context: "./gateway"
      dockerfile: dockerfile
    image: meta-web-three/gateway
    volumes:
      - ${DATA_PATH}/.data/gateway:/gateway
    ports:
      - "30001:30001"
    depends_on:
      mysql:
        - condition: service_healthy
      redis:
        condition: service_started
    networks:
      - meta-web-three
  backend-api:
    build:
      context: "./backend-api"
      dockerfile: dockerfile
    volumes:
      - ${DATA_PATH}/.data/backend-api:/
    ports:
      - "10082:10082"
      - "10083:10083"
    networks:
      - meta-web-three
    depends_on:
      mysql:
        - condition: service_healthy
      redis:
        condition: service_started
  client:
    build:
      context: "./client"
      dockerfile: dockerfile
    ports:
      - "30001:80"
    depends_on:
      backend-api:
        condition: service_started
networks:
  meta-web-three:
    driver: bridge
