version: '2'

include:
  - ./docker-compose.dataenv.yml
  - ./docker-compose.server.yml

services:
  client:
    build:
      context: "./client"
      dockerfile: dockerfile
    env_file:
      - ./client/.env
    ports:
      - "${VITE_PORT:-30001}:${VITE_PORT:-30001}"
    networks:
      - meta-web-three
networks:
  meta-web-three:
    driver: bridge
