version: '3'

services:
  zookeeper:
    image: ${ZOOKEEPER_IMAGE}
    container_name: zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}"
    restart: unless-stopped
    networks:
      - meta-web-three
  mysql:
    image: ${MYSQL_IMAGE}
    restart: always
    volumes:
      - ${DATA_PATH}/.data/mysql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    env_file:
      - .env
      - ./server/.env
    environment:
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=${TIMEZONE}
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --sql_mode=IGNORE_SPACE,NO_ENGINE_SUBSTITUTION
      --lower_case_table_names=2
    networks:
      - meta-web-three

  redis:
    image: ${REDIS_IMAGE}
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    env_file:
      - .env
      - ./server/.env
    volumes:
      - ${DATA_PATH}/.data/redis:/data
    networks:
      - meta-web-three

  rabbitmq:
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
    networks:
      - meta-web-three