# 注意：这个文件不应该包含真实的敏感信息
# 实际使用时应该使用外部Secret管理系统（如Vault、AWS Secrets Manager等）
# 或者使用 kubectl create secret 命令创建

apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: meta-web-three
type: Opaque
data:
  # 这些值应该从外部Secret管理系统获取
  # PostgreSQL配置示例：
  # 使用 kubectl create secret generic database-secret \
  #   --from-literal=postgres-password=your-password \
  #   --from-literal=postgres-username=your-username \
  #   --from-literal=postgres-database=your-database \
  #   -n meta-web-three
  postgres-password: <base64-encoded-password>
  postgres-username: <base64-encoded-username>
  postgres-database: <base64-encoded-database>
