# 引用镜像
FROM node:latest
# 作者
MAINTAINER WayLuk
# 创建文件夹
RUN mkdir -p /app
# 拷贝发布文件
COPY ./dist /app/dist
COPY ./node_modules /app/node_modules
COPY ./package*.json /app
COPY ./tsconfig.json /app
# 设定命令作用目录
WORKDIR /app
# 执行初始化
# RUN npm install
RUN npx prisma generate
RUN rm -rf ./dist/prisma

# 配置系统变量，指定端口
# ENV HOST 0.0.0.0
# ENV PORT 30001
# 开放端口
EXPOSE 30001
# 容器启动命令
CMD ["npm", "run" , "start:prod"]
