spring:
  config:
    import: 
      - optional:classpath:/application-dev.yml
      - optional:file:../src/main/resources/application-dev.yml
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.29.222.103:3306/metawebthree?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123123
aws:
  region: ap-southeast-1
  s3:
    buckets:
      product: metawebthree