---
server:
  port: 10083
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.29.222.103:3306/metawebthree?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123123
name: "meta-web-three"
project:
  author:
    name: "Way Luk"
    email: "lotaway@foxmail.com"
page-config:
  page-size: 20
# mybatis将SQL下划线字段自动转驼峰
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true