// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: OrderService.proto
// Protobuf Java Version: 4.32.0

@com.google.protobuf.Generated
public final class OrderServiceOuterClass {
  private OrderServiceOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      OrderServiceOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetOrderByUserIdRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetOrderByUserIdRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     * @return The id.
     */
    long getId();
  }
  /**
   * Protobuf type {@code GetOrderByUserIdRequest}
   */
  public static final class GetOrderByUserIdRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:GetOrderByUserIdRequest)
      GetOrderByUserIdRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 0,
        /* suffix= */ "",
        GetOrderByUserIdRequest.class.getName());
    }
    // Use GetOrderByUserIdRequest.newBuilder() to construct.
    private GetOrderByUserIdRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetOrderByUserIdRequest() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OrderServiceOuterClass.internal_static_GetOrderByUserIdRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OrderServiceOuterClass.internal_static_GetOrderByUserIdRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OrderServiceOuterClass.GetOrderByUserIdRequest.class, OrderServiceOuterClass.GetOrderByUserIdRequest.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>required int64 id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, id_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof OrderServiceOuterClass.GetOrderByUserIdRequest)) {
        return super.equals(obj);
      }
      OrderServiceOuterClass.GetOrderByUserIdRequest other = (OrderServiceOuterClass.GetOrderByUserIdRequest) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static OrderServiceOuterClass.GetOrderByUserIdRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OrderServiceOuterClass.GetOrderByUserIdRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OrderServiceOuterClass.GetOrderByUserIdRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OrderServiceOuterClass.GetOrderByUserIdRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OrderServiceOuterClass.GetOrderByUserIdRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OrderServiceOuterClass.GetOrderByUserIdRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OrderServiceOuterClass.GetOrderByUserIdRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static OrderServiceOuterClass.GetOrderByUserIdRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static OrderServiceOuterClass.GetOrderByUserIdRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static OrderServiceOuterClass.GetOrderByUserIdRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static OrderServiceOuterClass.GetOrderByUserIdRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static OrderServiceOuterClass.GetOrderByUserIdRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(OrderServiceOuterClass.GetOrderByUserIdRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetOrderByUserIdRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetOrderByUserIdRequest)
        OrderServiceOuterClass.GetOrderByUserIdRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return OrderServiceOuterClass.internal_static_GetOrderByUserIdRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return OrderServiceOuterClass.internal_static_GetOrderByUserIdRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OrderServiceOuterClass.GetOrderByUserIdRequest.class, OrderServiceOuterClass.GetOrderByUserIdRequest.Builder.class);
      }

      // Construct using OrderServiceOuterClass.GetOrderByUserIdRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return OrderServiceOuterClass.internal_static_GetOrderByUserIdRequest_descriptor;
      }

      @java.lang.Override
      public OrderServiceOuterClass.GetOrderByUserIdRequest getDefaultInstanceForType() {
        return OrderServiceOuterClass.GetOrderByUserIdRequest.getDefaultInstance();
      }

      @java.lang.Override
      public OrderServiceOuterClass.GetOrderByUserIdRequest build() {
        OrderServiceOuterClass.GetOrderByUserIdRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public OrderServiceOuterClass.GetOrderByUserIdRequest buildPartial() {
        OrderServiceOuterClass.GetOrderByUserIdRequest result = new OrderServiceOuterClass.GetOrderByUserIdRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(OrderServiceOuterClass.GetOrderByUserIdRequest result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OrderServiceOuterClass.GetOrderByUserIdRequest) {
          return mergeFrom((OrderServiceOuterClass.GetOrderByUserIdRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OrderServiceOuterClass.GetOrderByUserIdRequest other) {
        if (other == OrderServiceOuterClass.GetOrderByUserIdRequest.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       * @return Whether the id field is set.
       */
      @java.lang.Override
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GetOrderByUserIdRequest)
    }

    // @@protoc_insertion_point(class_scope:GetOrderByUserIdRequest)
    private static final OrderServiceOuterClass.GetOrderByUserIdRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new OrderServiceOuterClass.GetOrderByUserIdRequest();
    }

    public static OrderServiceOuterClass.GetOrderByUserIdRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetOrderByUserIdRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetOrderByUserIdRequest>() {
      @java.lang.Override
      public GetOrderByUserIdRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetOrderByUserIdRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetOrderByUserIdRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public OrderServiceOuterClass.GetOrderByUserIdRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetOrderByUserIdResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GetOrderByUserIdResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .OrderDTO orders = 1;</code>
     */
    java.util.List<OrderServiceOuterClass.OrderDTO> 
        getOrdersList();
    /**
     * <code>repeated .OrderDTO orders = 1;</code>
     */
    OrderServiceOuterClass.OrderDTO getOrders(int index);
    /**
     * <code>repeated .OrderDTO orders = 1;</code>
     */
    int getOrdersCount();
    /**
     * <code>repeated .OrderDTO orders = 1;</code>
     */
    java.util.List<? extends OrderServiceOuterClass.OrderDTOOrBuilder> 
        getOrdersOrBuilderList();
    /**
     * <code>repeated .OrderDTO orders = 1;</code>
     */
    OrderServiceOuterClass.OrderDTOOrBuilder getOrdersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code GetOrderByUserIdResponse}
   */
  public static final class GetOrderByUserIdResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:GetOrderByUserIdResponse)
      GetOrderByUserIdResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 0,
        /* suffix= */ "",
        GetOrderByUserIdResponse.class.getName());
    }
    // Use GetOrderByUserIdResponse.newBuilder() to construct.
    private GetOrderByUserIdResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetOrderByUserIdResponse() {
      orders_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OrderServiceOuterClass.internal_static_GetOrderByUserIdResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OrderServiceOuterClass.internal_static_GetOrderByUserIdResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OrderServiceOuterClass.GetOrderByUserIdResponse.class, OrderServiceOuterClass.GetOrderByUserIdResponse.Builder.class);
    }

    public static final int ORDERS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<OrderServiceOuterClass.OrderDTO> orders_;
    /**
     * <code>repeated .OrderDTO orders = 1;</code>
     */
    @java.lang.Override
    public java.util.List<OrderServiceOuterClass.OrderDTO> getOrdersList() {
      return orders_;
    }
    /**
     * <code>repeated .OrderDTO orders = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends OrderServiceOuterClass.OrderDTOOrBuilder> 
        getOrdersOrBuilderList() {
      return orders_;
    }
    /**
     * <code>repeated .OrderDTO orders = 1;</code>
     */
    @java.lang.Override
    public int getOrdersCount() {
      return orders_.size();
    }
    /**
     * <code>repeated .OrderDTO orders = 1;</code>
     */
    @java.lang.Override
    public OrderServiceOuterClass.OrderDTO getOrders(int index) {
      return orders_.get(index);
    }
    /**
     * <code>repeated .OrderDTO orders = 1;</code>
     */
    @java.lang.Override
    public OrderServiceOuterClass.OrderDTOOrBuilder getOrdersOrBuilder(
        int index) {
      return orders_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getOrdersCount(); i++) {
        if (!getOrders(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < orders_.size(); i++) {
        output.writeMessage(1, orders_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < orders_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, orders_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof OrderServiceOuterClass.GetOrderByUserIdResponse)) {
        return super.equals(obj);
      }
      OrderServiceOuterClass.GetOrderByUserIdResponse other = (OrderServiceOuterClass.GetOrderByUserIdResponse) obj;

      if (!getOrdersList()
          .equals(other.getOrdersList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getOrdersCount() > 0) {
        hash = (37 * hash) + ORDERS_FIELD_NUMBER;
        hash = (53 * hash) + getOrdersList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static OrderServiceOuterClass.GetOrderByUserIdResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OrderServiceOuterClass.GetOrderByUserIdResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OrderServiceOuterClass.GetOrderByUserIdResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OrderServiceOuterClass.GetOrderByUserIdResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OrderServiceOuterClass.GetOrderByUserIdResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OrderServiceOuterClass.GetOrderByUserIdResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OrderServiceOuterClass.GetOrderByUserIdResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static OrderServiceOuterClass.GetOrderByUserIdResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static OrderServiceOuterClass.GetOrderByUserIdResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static OrderServiceOuterClass.GetOrderByUserIdResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static OrderServiceOuterClass.GetOrderByUserIdResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static OrderServiceOuterClass.GetOrderByUserIdResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(OrderServiceOuterClass.GetOrderByUserIdResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GetOrderByUserIdResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GetOrderByUserIdResponse)
        OrderServiceOuterClass.GetOrderByUserIdResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return OrderServiceOuterClass.internal_static_GetOrderByUserIdResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return OrderServiceOuterClass.internal_static_GetOrderByUserIdResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OrderServiceOuterClass.GetOrderByUserIdResponse.class, OrderServiceOuterClass.GetOrderByUserIdResponse.Builder.class);
      }

      // Construct using OrderServiceOuterClass.GetOrderByUserIdResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (ordersBuilder_ == null) {
          orders_ = java.util.Collections.emptyList();
        } else {
          orders_ = null;
          ordersBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return OrderServiceOuterClass.internal_static_GetOrderByUserIdResponse_descriptor;
      }

      @java.lang.Override
      public OrderServiceOuterClass.GetOrderByUserIdResponse getDefaultInstanceForType() {
        return OrderServiceOuterClass.GetOrderByUserIdResponse.getDefaultInstance();
      }

      @java.lang.Override
      public OrderServiceOuterClass.GetOrderByUserIdResponse build() {
        OrderServiceOuterClass.GetOrderByUserIdResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public OrderServiceOuterClass.GetOrderByUserIdResponse buildPartial() {
        OrderServiceOuterClass.GetOrderByUserIdResponse result = new OrderServiceOuterClass.GetOrderByUserIdResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(OrderServiceOuterClass.GetOrderByUserIdResponse result) {
        if (ordersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            orders_ = java.util.Collections.unmodifiableList(orders_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.orders_ = orders_;
        } else {
          result.orders_ = ordersBuilder_.build();
        }
      }

      private void buildPartial0(OrderServiceOuterClass.GetOrderByUserIdResponse result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OrderServiceOuterClass.GetOrderByUserIdResponse) {
          return mergeFrom((OrderServiceOuterClass.GetOrderByUserIdResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OrderServiceOuterClass.GetOrderByUserIdResponse other) {
        if (other == OrderServiceOuterClass.GetOrderByUserIdResponse.getDefaultInstance()) return this;
        if (ordersBuilder_ == null) {
          if (!other.orders_.isEmpty()) {
            if (orders_.isEmpty()) {
              orders_ = other.orders_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureOrdersIsMutable();
              orders_.addAll(other.orders_);
            }
            onChanged();
          }
        } else {
          if (!other.orders_.isEmpty()) {
            if (ordersBuilder_.isEmpty()) {
              ordersBuilder_.dispose();
              ordersBuilder_ = null;
              orders_ = other.orders_;
              bitField0_ = (bitField0_ & ~0x00000001);
              ordersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetOrdersFieldBuilder() : null;
            } else {
              ordersBuilder_.addAllMessages(other.orders_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getOrdersCount(); i++) {
          if (!getOrders(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                OrderServiceOuterClass.OrderDTO m =
                    input.readMessage(
                        OrderServiceOuterClass.OrderDTO.parser(),
                        extensionRegistry);
                if (ordersBuilder_ == null) {
                  ensureOrdersIsMutable();
                  orders_.add(m);
                } else {
                  ordersBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<OrderServiceOuterClass.OrderDTO> orders_ =
        java.util.Collections.emptyList();
      private void ensureOrdersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          orders_ = new java.util.ArrayList<OrderServiceOuterClass.OrderDTO>(orders_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          OrderServiceOuterClass.OrderDTO, OrderServiceOuterClass.OrderDTO.Builder, OrderServiceOuterClass.OrderDTOOrBuilder> ordersBuilder_;

      /**
       * <code>repeated .OrderDTO orders = 1;</code>
       */
      public java.util.List<OrderServiceOuterClass.OrderDTO> getOrdersList() {
        if (ordersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(orders_);
        } else {
          return ordersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .OrderDTO orders = 1;</code>
       */
      public int getOrdersCount() {
        if (ordersBuilder_ == null) {
          return orders_.size();
        } else {
          return ordersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .OrderDTO orders = 1;</code>
       */
      public OrderServiceOuterClass.OrderDTO getOrders(int index) {
        if (ordersBuilder_ == null) {
          return orders_.get(index);
        } else {
          return ordersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .OrderDTO orders = 1;</code>
       */
      public Builder setOrders(
          int index, OrderServiceOuterClass.OrderDTO value) {
        if (ordersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrdersIsMutable();
          orders_.set(index, value);
          onChanged();
        } else {
          ordersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .OrderDTO orders = 1;</code>
       */
      public Builder setOrders(
          int index, OrderServiceOuterClass.OrderDTO.Builder builderForValue) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          orders_.set(index, builderForValue.build());
          onChanged();
        } else {
          ordersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .OrderDTO orders = 1;</code>
       */
      public Builder addOrders(OrderServiceOuterClass.OrderDTO value) {
        if (ordersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrdersIsMutable();
          orders_.add(value);
          onChanged();
        } else {
          ordersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .OrderDTO orders = 1;</code>
       */
      public Builder addOrders(
          int index, OrderServiceOuterClass.OrderDTO value) {
        if (ordersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrdersIsMutable();
          orders_.add(index, value);
          onChanged();
        } else {
          ordersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .OrderDTO orders = 1;</code>
       */
      public Builder addOrders(
          OrderServiceOuterClass.OrderDTO.Builder builderForValue) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          orders_.add(builderForValue.build());
          onChanged();
        } else {
          ordersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .OrderDTO orders = 1;</code>
       */
      public Builder addOrders(
          int index, OrderServiceOuterClass.OrderDTO.Builder builderForValue) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          orders_.add(index, builderForValue.build());
          onChanged();
        } else {
          ordersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .OrderDTO orders = 1;</code>
       */
      public Builder addAllOrders(
          java.lang.Iterable<? extends OrderServiceOuterClass.OrderDTO> values) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, orders_);
          onChanged();
        } else {
          ordersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .OrderDTO orders = 1;</code>
       */
      public Builder clearOrders() {
        if (ordersBuilder_ == null) {
          orders_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          ordersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .OrderDTO orders = 1;</code>
       */
      public Builder removeOrders(int index) {
        if (ordersBuilder_ == null) {
          ensureOrdersIsMutable();
          orders_.remove(index);
          onChanged();
        } else {
          ordersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .OrderDTO orders = 1;</code>
       */
      public OrderServiceOuterClass.OrderDTO.Builder getOrdersBuilder(
          int index) {
        return internalGetOrdersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .OrderDTO orders = 1;</code>
       */
      public OrderServiceOuterClass.OrderDTOOrBuilder getOrdersOrBuilder(
          int index) {
        if (ordersBuilder_ == null) {
          return orders_.get(index);  } else {
          return ordersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .OrderDTO orders = 1;</code>
       */
      public java.util.List<? extends OrderServiceOuterClass.OrderDTOOrBuilder> 
           getOrdersOrBuilderList() {
        if (ordersBuilder_ != null) {
          return ordersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(orders_);
        }
      }
      /**
       * <code>repeated .OrderDTO orders = 1;</code>
       */
      public OrderServiceOuterClass.OrderDTO.Builder addOrdersBuilder() {
        return internalGetOrdersFieldBuilder().addBuilder(
            OrderServiceOuterClass.OrderDTO.getDefaultInstance());
      }
      /**
       * <code>repeated .OrderDTO orders = 1;</code>
       */
      public OrderServiceOuterClass.OrderDTO.Builder addOrdersBuilder(
          int index) {
        return internalGetOrdersFieldBuilder().addBuilder(
            index, OrderServiceOuterClass.OrderDTO.getDefaultInstance());
      }
      /**
       * <code>repeated .OrderDTO orders = 1;</code>
       */
      public java.util.List<OrderServiceOuterClass.OrderDTO.Builder> 
           getOrdersBuilderList() {
        return internalGetOrdersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          OrderServiceOuterClass.OrderDTO, OrderServiceOuterClass.OrderDTO.Builder, OrderServiceOuterClass.OrderDTOOrBuilder> 
          internalGetOrdersFieldBuilder() {
        if (ordersBuilder_ == null) {
          ordersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              OrderServiceOuterClass.OrderDTO, OrderServiceOuterClass.OrderDTO.Builder, OrderServiceOuterClass.OrderDTOOrBuilder>(
                  orders_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          orders_ = null;
        }
        return ordersBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:GetOrderByUserIdResponse)
    }

    // @@protoc_insertion_point(class_scope:GetOrderByUserIdResponse)
    private static final OrderServiceOuterClass.GetOrderByUserIdResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new OrderServiceOuterClass.GetOrderByUserIdResponse();
    }

    public static OrderServiceOuterClass.GetOrderByUserIdResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetOrderByUserIdResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetOrderByUserIdResponse>() {
      @java.lang.Override
      public GetOrderByUserIdResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetOrderByUserIdResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetOrderByUserIdResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public OrderServiceOuterClass.GetOrderByUserIdResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OrderDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OrderDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>required int64 userId = 2;</code>
     * @return Whether the userId field is set.
     */
    boolean hasUserId();
    /**
     * <code>required int64 userId = 2;</code>
     * @return The userId.
     */
    long getUserId();

    /**
     * <code>required string orderNo = 3;</code>
     * @return Whether the orderNo field is set.
     */
    boolean hasOrderNo();
    /**
     * <code>required string orderNo = 3;</code>
     * @return The orderNo.
     */
    java.lang.String getOrderNo();
    /**
     * <code>required string orderNo = 3;</code>
     * @return The bytes for orderNo.
     */
    com.google.protobuf.ByteString
        getOrderNoBytes();

    /**
     * <code>required string orderStatus = 4;</code>
     * @return Whether the orderStatus field is set.
     */
    boolean hasOrderStatus();
    /**
     * <code>required string orderStatus = 4;</code>
     * @return The orderStatus.
     */
    java.lang.String getOrderStatus();
    /**
     * <code>required string orderStatus = 4;</code>
     * @return The bytes for orderStatus.
     */
    com.google.protobuf.ByteString
        getOrderStatusBytes();

    /**
     * <code>required string orderType = 5;</code>
     * @return Whether the orderType field is set.
     */
    boolean hasOrderType();
    /**
     * <code>required string orderType = 5;</code>
     * @return The orderType.
     */
    java.lang.String getOrderType();
    /**
     * <code>required string orderType = 5;</code>
     * @return The bytes for orderType.
     */
    com.google.protobuf.ByteString
        getOrderTypeBytes();

    /**
     * <code>required double orderAmount = 6;</code>
     * @return Whether the orderAmount field is set.
     */
    boolean hasOrderAmount();
    /**
     * <code>required double orderAmount = 6;</code>
     * @return The orderAmount.
     */
    double getOrderAmount();
  }
  /**
   * Protobuf type {@code OrderDTO}
   */
  public static final class OrderDTO extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:OrderDTO)
      OrderDTOOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 0,
        /* suffix= */ "",
        OrderDTO.class.getName());
    }
    // Use OrderDTO.newBuilder() to construct.
    private OrderDTO(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private OrderDTO() {
      orderNo_ = "";
      orderStatus_ = "";
      orderType_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OrderServiceOuterClass.internal_static_OrderDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OrderServiceOuterClass.internal_static_OrderDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OrderServiceOuterClass.OrderDTO.class, OrderServiceOuterClass.OrderDTO.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>required int64 id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private long userId_ = 0L;
    /**
     * <code>required int64 userId = 2;</code>
     * @return Whether the userId field is set.
     */
    @java.lang.Override
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int64 userId = 2;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }

    public static final int ORDERNO_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object orderNo_ = "";
    /**
     * <code>required string orderNo = 3;</code>
     * @return Whether the orderNo field is set.
     */
    @java.lang.Override
    public boolean hasOrderNo() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string orderNo = 3;</code>
     * @return The orderNo.
     */
    @java.lang.Override
    public java.lang.String getOrderNo() {
      java.lang.Object ref = orderNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          orderNo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string orderNo = 3;</code>
     * @return The bytes for orderNo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOrderNoBytes() {
      java.lang.Object ref = orderNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDERSTATUS_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object orderStatus_ = "";
    /**
     * <code>required string orderStatus = 4;</code>
     * @return Whether the orderStatus field is set.
     */
    @java.lang.Override
    public boolean hasOrderStatus() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required string orderStatus = 4;</code>
     * @return The orderStatus.
     */
    @java.lang.Override
    public java.lang.String getOrderStatus() {
      java.lang.Object ref = orderStatus_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          orderStatus_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string orderStatus = 4;</code>
     * @return The bytes for orderStatus.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOrderStatusBytes() {
      java.lang.Object ref = orderStatus_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDERTYPE_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object orderType_ = "";
    /**
     * <code>required string orderType = 5;</code>
     * @return Whether the orderType field is set.
     */
    @java.lang.Override
    public boolean hasOrderType() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required string orderType = 5;</code>
     * @return The orderType.
     */
    @java.lang.Override
    public java.lang.String getOrderType() {
      java.lang.Object ref = orderType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          orderType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string orderType = 5;</code>
     * @return The bytes for orderType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOrderTypeBytes() {
      java.lang.Object ref = orderType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDERAMOUNT_FIELD_NUMBER = 6;
    private double orderAmount_ = 0D;
    /**
     * <code>required double orderAmount = 6;</code>
     * @return Whether the orderAmount field is set.
     */
    @java.lang.Override
    public boolean hasOrderAmount() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required double orderAmount = 6;</code>
     * @return The orderAmount.
     */
    @java.lang.Override
    public double getOrderAmount() {
      return orderAmount_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOrderNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOrderStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOrderType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOrderAmount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, userId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, orderNo_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, orderStatus_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, orderType_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeDouble(6, orderAmount_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, userId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, orderNo_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, orderStatus_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, orderType_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, orderAmount_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof OrderServiceOuterClass.OrderDTO)) {
        return super.equals(obj);
      }
      OrderServiceOuterClass.OrderDTO other = (OrderServiceOuterClass.OrderDTO) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (hasUserId() != other.hasUserId()) return false;
      if (hasUserId()) {
        if (getUserId()
            != other.getUserId()) return false;
      }
      if (hasOrderNo() != other.hasOrderNo()) return false;
      if (hasOrderNo()) {
        if (!getOrderNo()
            .equals(other.getOrderNo())) return false;
      }
      if (hasOrderStatus() != other.hasOrderStatus()) return false;
      if (hasOrderStatus()) {
        if (!getOrderStatus()
            .equals(other.getOrderStatus())) return false;
      }
      if (hasOrderType() != other.hasOrderType()) return false;
      if (hasOrderType()) {
        if (!getOrderType()
            .equals(other.getOrderType())) return false;
      }
      if (hasOrderAmount() != other.hasOrderAmount()) return false;
      if (hasOrderAmount()) {
        if (java.lang.Double.doubleToLongBits(getOrderAmount())
            != java.lang.Double.doubleToLongBits(
                other.getOrderAmount())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
      }
      if (hasUserId()) {
        hash = (37 * hash) + USERID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getUserId());
      }
      if (hasOrderNo()) {
        hash = (37 * hash) + ORDERNO_FIELD_NUMBER;
        hash = (53 * hash) + getOrderNo().hashCode();
      }
      if (hasOrderStatus()) {
        hash = (37 * hash) + ORDERSTATUS_FIELD_NUMBER;
        hash = (53 * hash) + getOrderStatus().hashCode();
      }
      if (hasOrderType()) {
        hash = (37 * hash) + ORDERTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getOrderType().hashCode();
      }
      if (hasOrderAmount()) {
        hash = (37 * hash) + ORDERAMOUNT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getOrderAmount()));
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static OrderServiceOuterClass.OrderDTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OrderServiceOuterClass.OrderDTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OrderServiceOuterClass.OrderDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OrderServiceOuterClass.OrderDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OrderServiceOuterClass.OrderDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OrderServiceOuterClass.OrderDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OrderServiceOuterClass.OrderDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static OrderServiceOuterClass.OrderDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static OrderServiceOuterClass.OrderDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static OrderServiceOuterClass.OrderDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static OrderServiceOuterClass.OrderDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static OrderServiceOuterClass.OrderDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(OrderServiceOuterClass.OrderDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OrderDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OrderDTO)
        OrderServiceOuterClass.OrderDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return OrderServiceOuterClass.internal_static_OrderDTO_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return OrderServiceOuterClass.internal_static_OrderDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OrderServiceOuterClass.OrderDTO.class, OrderServiceOuterClass.OrderDTO.Builder.class);
      }

      // Construct using OrderServiceOuterClass.OrderDTO.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        userId_ = 0L;
        orderNo_ = "";
        orderStatus_ = "";
        orderType_ = "";
        orderAmount_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return OrderServiceOuterClass.internal_static_OrderDTO_descriptor;
      }

      @java.lang.Override
      public OrderServiceOuterClass.OrderDTO getDefaultInstanceForType() {
        return OrderServiceOuterClass.OrderDTO.getDefaultInstance();
      }

      @java.lang.Override
      public OrderServiceOuterClass.OrderDTO build() {
        OrderServiceOuterClass.OrderDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public OrderServiceOuterClass.OrderDTO buildPartial() {
        OrderServiceOuterClass.OrderDTO result = new OrderServiceOuterClass.OrderDTO(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(OrderServiceOuterClass.OrderDTO result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.userId_ = userId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.orderNo_ = orderNo_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.orderStatus_ = orderStatus_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.orderType_ = orderType_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.orderAmount_ = orderAmount_;
          to_bitField0_ |= 0x00000020;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OrderServiceOuterClass.OrderDTO) {
          return mergeFrom((OrderServiceOuterClass.OrderDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OrderServiceOuterClass.OrderDTO other) {
        if (other == OrderServiceOuterClass.OrderDTO.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasOrderNo()) {
          orderNo_ = other.orderNo_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasOrderStatus()) {
          orderStatus_ = other.orderStatus_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.hasOrderType()) {
          orderType_ = other.orderType_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.hasOrderAmount()) {
          setOrderAmount(other.getOrderAmount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasUserId()) {
          return false;
        }
        if (!hasOrderNo()) {
          return false;
        }
        if (!hasOrderStatus()) {
          return false;
        }
        if (!hasOrderType()) {
          return false;
        }
        if (!hasOrderAmount()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                userId_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                orderNo_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                orderStatus_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                orderType_ = input.readBytes();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 49: {
                orderAmount_ = input.readDouble();
                bitField0_ |= 0x00000020;
                break;
              } // case 49
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       * @return Whether the id field is set.
       */
      @java.lang.Override
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <code>required int64 userId = 2;</code>
       * @return Whether the userId field is set.
       */
      @java.lang.Override
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int64 userId = 2;</code>
       * @return The userId.
       */
      @java.lang.Override
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>required int64 userId = 2;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {

        userId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 userId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object orderNo_ = "";
      /**
       * <code>required string orderNo = 3;</code>
       * @return Whether the orderNo field is set.
       */
      public boolean hasOrderNo() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required string orderNo = 3;</code>
       * @return The orderNo.
       */
      public java.lang.String getOrderNo() {
        java.lang.Object ref = orderNo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            orderNo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string orderNo = 3;</code>
       * @return The bytes for orderNo.
       */
      public com.google.protobuf.ByteString
          getOrderNoBytes() {
        java.lang.Object ref = orderNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string orderNo = 3;</code>
       * @param value The orderNo to set.
       * @return This builder for chaining.
       */
      public Builder setOrderNo(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        orderNo_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>required string orderNo = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderNo() {
        orderNo_ = getDefaultInstance().getOrderNo();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>required string orderNo = 3;</code>
       * @param value The bytes for orderNo to set.
       * @return This builder for chaining.
       */
      public Builder setOrderNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        orderNo_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object orderStatus_ = "";
      /**
       * <code>required string orderStatus = 4;</code>
       * @return Whether the orderStatus field is set.
       */
      public boolean hasOrderStatus() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required string orderStatus = 4;</code>
       * @return The orderStatus.
       */
      public java.lang.String getOrderStatus() {
        java.lang.Object ref = orderStatus_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            orderStatus_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string orderStatus = 4;</code>
       * @return The bytes for orderStatus.
       */
      public com.google.protobuf.ByteString
          getOrderStatusBytes() {
        java.lang.Object ref = orderStatus_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderStatus_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string orderStatus = 4;</code>
       * @param value The orderStatus to set.
       * @return This builder for chaining.
       */
      public Builder setOrderStatus(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        orderStatus_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>required string orderStatus = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderStatus() {
        orderStatus_ = getDefaultInstance().getOrderStatus();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>required string orderStatus = 4;</code>
       * @param value The bytes for orderStatus to set.
       * @return This builder for chaining.
       */
      public Builder setOrderStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        orderStatus_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object orderType_ = "";
      /**
       * <code>required string orderType = 5;</code>
       * @return Whether the orderType field is set.
       */
      public boolean hasOrderType() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required string orderType = 5;</code>
       * @return The orderType.
       */
      public java.lang.String getOrderType() {
        java.lang.Object ref = orderType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            orderType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string orderType = 5;</code>
       * @return The bytes for orderType.
       */
      public com.google.protobuf.ByteString
          getOrderTypeBytes() {
        java.lang.Object ref = orderType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string orderType = 5;</code>
       * @param value The orderType to set.
       * @return This builder for chaining.
       */
      public Builder setOrderType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        orderType_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>required string orderType = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderType() {
        orderType_ = getDefaultInstance().getOrderType();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>required string orderType = 5;</code>
       * @param value The bytes for orderType to set.
       * @return This builder for chaining.
       */
      public Builder setOrderTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        orderType_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private double orderAmount_ ;
      /**
       * <code>required double orderAmount = 6;</code>
       * @return Whether the orderAmount field is set.
       */
      @java.lang.Override
      public boolean hasOrderAmount() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required double orderAmount = 6;</code>
       * @return The orderAmount.
       */
      @java.lang.Override
      public double getOrderAmount() {
        return orderAmount_;
      }
      /**
       * <code>required double orderAmount = 6;</code>
       * @param value The orderAmount to set.
       * @return This builder for chaining.
       */
      public Builder setOrderAmount(double value) {

        orderAmount_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>required double orderAmount = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderAmount() {
        bitField0_ = (bitField0_ & ~0x00000020);
        orderAmount_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:OrderDTO)
    }

    // @@protoc_insertion_point(class_scope:OrderDTO)
    private static final OrderServiceOuterClass.OrderDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new OrderServiceOuterClass.OrderDTO();
    }

    public static OrderServiceOuterClass.OrderDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrderDTO>
        PARSER = new com.google.protobuf.AbstractParser<OrderDTO>() {
      @java.lang.Override
      public OrderDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<OrderDTO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OrderDTO> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public OrderServiceOuterClass.OrderDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetOrderByUserIdRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetOrderByUserIdRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetOrderByUserIdResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GetOrderByUserIdResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderDTO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OrderDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022OrderService.proto\"%\n\027GetOrderByUserId" +
      "Request\022\n\n\002id\030\001 \002(\003\"5\n\030GetOrderByUserIdR" +
      "esponse\022\031\n\006orders\030\001 \003(\0132\t.OrderDTO\"t\n\010Or" +
      "derDTO\022\n\n\002id\030\001 \002(\003\022\016\n\006userId\030\002 \002(\003\022\017\n\007or" +
      "derNo\030\003 \002(\t\022\023\n\013orderStatus\030\004 \002(\t\022\021\n\torde" +
      "rType\030\005 \002(\t\022\023\n\013orderAmount\030\006 \002(\0012W\n\014Orde" +
      "rService\022G\n\020getOrderByUserId\022\030.GetOrderB" +
      "yUserIdRequest\032\031.GetOrderByUserIdRespons" +
      "e"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GetOrderByUserIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetOrderByUserIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetOrderByUserIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetOrderByUserIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetOrderByUserIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GetOrderByUserIdResponse_descriptor,
        new java.lang.String[] { "Orders", });
    internal_static_OrderDTO_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_OrderDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_OrderDTO_descriptor,
        new java.lang.String[] { "Id", "UserId", "OrderNo", "OrderStatus", "OrderType", "OrderAmount", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
