---
spring:
  application:
    name: server
---
spring:
  profiles:
    active: user-service, product-service, order-service, message-service
# rocketMQ
rocketmq:
  client:
    namesrv: 192.168.43.137:9876