---
server:
  port: 10083
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.29.222.103:3306/metawebthree
    username: root
    password: 123123
name: "meta-web-three"
author:
  name: "Way Luk"
  email: "lotaway@foxmail.com"
---
server:
  port: 10083
spring:
  config:
    activate:
      on-profile: pro
---
spring:
  profiles:
    active: dev
