server:
  port: 10098
spring:
  application:
    name: risk-control-service
  profiles:
    active: dev
dubbo:
  protocol:
    name: tri
    port: 20887
---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-common-dev.yml
---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-common-prod.yml