server:
  port: 10115
spring:
  application:
    name: developer-portal-service
  profiles:
    active: dev
dubbo:
  application:
    name: developer-portal-service
  protocol:
    port: 20115

notification:
  email:
    enabled: ${EMAIL_ENABLED:true}

service-governance:
  rate-limiter:
    developerRegister:
      enabled: true
      limit-for-period: 3
      limit-refresh-period: 60s
      timeout-duration: 5s
---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-common-dev.yml
---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-common-prod.yml
