server:
  port: 10115
spring:
  application:
    name: developer-portal-service
  profiles:
    active: dev
dubbo:
  application:
    name: developer-portal-service
  protocol:
    port: 20115
---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-common-dev.yml
---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-common-prod.yml
