version: '3.8'

services:
  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped

  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8080:8080"
    command: ["java", "-jar", "/product-servie.jar"]
    depends_on:
      - zookeeper
    restart: unless-stopped

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8081:8081"
    command: ["java", "-jar", "/user-servie.jar"]
    depends_on:
      - zookeeper
    restart: unless-stopped

  message-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: message-service
    ports:
      - "8082:8082"
    command: ["java", "-jar", "/message-service.jar"]
    depends_on:
      - zookeeper
    restart: unless-stopped