server:
  port: 10085
spring:
  application:
    name: message-service
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
    import: 
      # - optional:classpath:/config/application-common-${spring.profiles.active}.yml
      - optional:classpath:application-common.yml
      - optional:classpath:application-common-dev.yml
---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-common-prod.yml