name: meta-web-three-ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.11.13
  - pip:
  # pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/
    - --index-url https://pypi.tuna.tsinghua.edu.cn/simple
    - numpy>=1.21.0
    - onnxruntime>=1.22.1
    - apache-dubbo>=3.0.0b1
    - python-dotenv>=1.1.1
    - orjson>=3.11.2