name: meta-web-three-ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.0
  - pip:
  # pip config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
    - --index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
    - numpy>=1.21.0
    - onnxruntime>=1.22.1
    - python3-dubbo>=0.0.8
    # - apache-dubbo>=3.0.0b1