create TABLE User {
    id BIGINT PRIMARY KEY,
    username VARCHAR(20) NOT NULL UNIQUE,
    nickname VARCHAR(20),
    avatar VARCHAR(255),
    email VARCHAR(30) UNIQUE,
    password VARCHAR(16) NOT NULL,
    type_id SMALLINT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
}

CREATE TABLE User_Role {
    id SMALLINT PRIMARY KEY AUTO_INCREMENT,
    role SMALLINT NOT NULL UNIQUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
}

CREATE TABLE User_Role_Mapping {
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL REFERENCES User(id),
    user_role_id SMALLINT NOT NULL REFERENCES UserRole(id),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
}

CREATE TABLE Web3_User {
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES User(id),
    wallet_address VARCHAR(255) NOT NULL UNIQUE,
    chain_id SMALLINT NOT NULL,
    chain_type VARCHAR(10) NOT NULL DEFAULT "mainnet",
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
}

CREATE TABLE Author {
    id INTEGER PRIMARY KEY,
    real_name VARCHAR(20) NOT NULL,
    is_enable BOOLEAN NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
}

CREATE TABLE Author_User_Mapping {
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    author_id INTEGER NOT NULL REFERENCES Author(id),
    user_id BIGINT NOT NULL REFERENCES User(id),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
}

CREATE INDEX idx_web3_user_wallet_address ON Web3_User (wallet_address);