create TABLE User {
    id BIGINT PRIMARY KEY,
    username VARCHAR(20) NOT NULL UNIQUE,
    nickname VARCHAR(20),
    avatar VARCHAR(255),
    email VARCHAR(30) UNIQUE,
    password VARCHAR(16) NOT NULL,
    type_id SMALLINT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
}

CREATE TABLE UserRole {
    id SMALLINT PRIMARY KEY AUTO_INCREMENT,
    role SMALLINT NOT NULL UNIQUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
}

CREATE TABLE UserRoleMapping {
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL REFERENCES User(id),
    user_role_id SMALLINT NOT NULL REFERENCES UserRole(id),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
}

CREATE TABLE web3_user {
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES User(id),
    wallet_address VARCHAR(255) NOT NULL UNIQUE,
    chain_id SMALLINT NOT NULL,
    chain_type VARCHAR(10) NOT NULL DEFAULT "mainnet",
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
}

CREATE INDEX idx_web3_user_wallet_address ON web3_user (wallet_address);