create TABLE User {
    id BIGINT PRIMARY KEY,
    username VARCHAR(20) NOT NULL UNIQUE,
    nickname VARCHAR(20),
    avatar VARCHAR(255),
    email VARCHAR(30) UNIQUE,
    password VARCHAR(16) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
}

CREATE TABLE User_Role {
    id SMALLINT PRIMARY KEY AUTO_INCREMENT,
    role SMALLINT NOT NULL UNIQUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
}

CREATE TABLE User_Role_Mapping {
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL REFERENCES User(id),
    user_role_id SMALLINT NOT NULL REFERENCES UserRole(id),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
}

CREATE TABLE Web3_User {
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES User(id),
    wallet_address VARCHAR(255) NOT NULL UNIQUE,
    chain_id SMALLINT NOT NULL,
    chain_type VARCHAR(10) NOT NULL DEFAULT "mainnet",
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
}

CREATE TABLE Author {
    id INTEGER PRIMARY KEY,
    real_name VARCHAR(20) NOT NULL,
    is_enable BOOLEAN NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
}

CREATE TABLE Author_User_Mapping {
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    author_id INTEGER NOT NULL REFERENCES Author(id),
    user_id BIGINT NOT NULL REFERENCES User(id),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
}

CREATE INDEX idx_web3_user_wallet_address ON Web3_User (wallet_address);

CREATE TABLE TokenMapping (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    parent_token VARCHAR(512) NOT NULL,
    child_token VARCHAR(512) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES User (id),
    permissions VARCHAR(255) COMMENT '子token权限，逗号分隔',
    expires_at DATETIME NOT NULL,
    is_revoked BOOLEAN NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_parent_token (parent_token),
    INDEX idx_child_token (child_token),
    INDEX idx_user_id (user_id),
    INDEX idx_expires_at (expires_at)
);

CREATE TABLE user_profile (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL REFERENCES User (id),
    age INTEGER,
    external_debt_ratio FLOAT COMMENT '外部债务比率',
    gps_stability FLOAT COMMENT 'GPS稳定性(0-1)',
    device_shared_degree INTEGER COMMENT '设备共享程度(关联账号数)',
    device_risk_tag VARCHAR(255) COMMENT '设备风险标签(如ROOT,EMULATOR)',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_user_id (user_id)
);