-- USER SERVICE INITIAL SCHEMA
-- Enhanced with Member management fields and tables based on mall requirements

CREATE TABLE "User" (
    id BIGINT PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    nickname VARCHAR(64),
    avatar VARCHAR(255),
    email VARCHAR(100) UNIQUE,
    password VARCHAR(64) NOT NULL,
    phone VARCHAR(32) UNIQUE,
    status SMALLINT DEFAULT 1, -- 0->disabled, 1->enabled
    gender INT DEFAULT 0, -- 0->unknown, 1->male, 2->female
    birthday DATE,
    city VARCHAR(100),
    job VARCHAR(100),
    personalized_signature VARCHAR(255),
    integration INT DEFAULT 0,
    growth INT DEFAULT 0,
    member_level_id BIGINT,
    source_type INT DEFAULT 0,
    type_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "User_Role" (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role SMALLINT NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "User_Role_Mapping" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES "User"(id),
    user_role_id SMALLINT NOT NULL REFERENCES "User_Role"(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Web3_User" (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES "User"(id),
    wallet_address VARCHAR(255) NOT NULL UNIQUE,
    chain_id SMALLINT NOT NULL,
    chain_type VARCHAR(10) NOT NULL DEFAULT 'mainnet',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_web3_user_wallet_address ON "Web3_User" (wallet_address);

CREATE TABLE "Author" (
    id INTEGER PRIMARY KEY,
    real_name VARCHAR(64) NOT NULL,
    is_enable BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Author_User_Mapping" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id INTEGER NOT NULL REFERENCES "Author"(id),
    user_id BIGINT NOT NULL REFERENCES "User"(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "tb_member_level" (
    id BIGINT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    growth_point INT DEFAULT 0,
    default_status SMALLINT DEFAULT 0,
    free_freight_point DECIMAL(10, 2),
    comment_growth_point INT DEFAULT 0,
    priviledge_free_freight SMALLINT DEFAULT 0,
    priviledge_sign_in SMALLINT DEFAULT 0,
    priviledge_comment SMALLINT DEFAULT 0,
    priviledge_promotion SMALLINT DEFAULT 0,
    priviledge_member_price SMALLINT DEFAULT 0,
    priviledge_birthday SMALLINT DEFAULT 0,
    note VARCHAR(255)
);

CREATE TABLE "tb_member_receive_address" (
    id BIGINT PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES "User"(id),
    name VARCHAR(100),
    phone_number VARCHAR(32),
    default_status SMALLINT DEFAULT 0,
    post_code VARCHAR(32),
    province VARCHAR(64),
    city VARCHAR(64),
    region VARCHAR(64),
    detail_address VARCHAR(255)
);

CREATE TABLE "tb_member_login_log" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES "User"(id),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ip VARCHAR(64),
    city VARCHAR(64),
    login_type INT, -- 0->PC, 1->APP, 2->Web3
    province VARCHAR(64)
);

CREATE TABLE "tb_integration_consume_setting" (
    id BIGINT PRIMARY KEY,
    deduction_per_amount INT,
    max_percent_per_order INT,
    use_unit INT,
    coupon_status SMALLINT
);

CREATE TABLE "tb_growth_change_history" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES "User"(id),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    change_type INT, -- 0->Order, 1->Sign, etc
    change_count INT,
    operate_man VARCHAR(100),
    operate_note VARCHAR(255),
    source_type INT
);

CREATE TABLE "tb_integration_change_history" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES "User"(id),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    change_type INT,
    change_count INT,
    operate_man VARCHAR(100),
    operate_note VARCHAR(255),
    source_type INT
);

CREATE TABLE "user_profile" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES "User" (id),
    age INTEGER,
    external_debt_ratio FLOAT,
    gps_stability FLOAT,
    device_shared_degree INTEGER,
    device_risk_tag VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_user_profile_user_id ON user_profile (user_id);

CREATE TABLE "TokenMapping" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_token VARCHAR(512) NOT NULL,
    child_token VARCHAR(512) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES "User" (id),
    permissions VARCHAR(255),
    expires_at TIMESTAMP NOT NULL,
    is_revoked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_parent_token ON "TokenMapping" (parent_token);
CREATE INDEX idx_child_token ON "TokenMapping" (child_token);
CREATE INDEX idx_user_id_token ON "TokenMapping" (user_id);
