CREATE TABLE IF NOT EXISTS tb_vehicle (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    vehicle_code    VARCHAR(50)  NOT NULL UNIQUE COMMENT '车辆编码',
    vehicle_number  VARCHAR(50)  NOT NULL UNIQUE COMMENT '车牌号',
    vehicle_type    VARCHAR(50)  NULL     COMMENT '车辆类型',
    status          VARCHAR(20)  NOT NULL DEFAULT 'IDLE' COMMENT '状态:IDLE,ASSIGNED,IN_TRANSIT,MAINTENANCE,OFFLINE',
    max_load_capacity DECIMAL(10,2) NULL  COMMENT '最大载重(kg)',
    current_load    DECIMAL(10,2) NULL  DEFAULT 0 COMMENT '当前载重(kg)',
    fuel_capacity   DECIMAL(10,2) NULL  COMMENT '油箱容量(L)',
    current_fuel    DECIMAL(10,2) NULL  DEFAULT 0 COMMENT '当前油量(L)',
    fuel_efficiency DECIMAL(10,4) NULL  COMMENT '燃油效率(km/L)',
    driver_name     VARCHAR(50)  NULL     COMMENT '司机姓名',
    driver_phone    VARCHAR(20)  NULL     COMMENT '司机电话',
    latitude        DECIMAL(10,6) NULL    COMMENT '纬度',
    longitude       DECIMAL(10,6) NULL    COMMENT '经度',
    last_location_update DATETIME NULL    COMMENT '最后位置更新时间',
    current_route_plan_code VARCHAR(50) NULL COMMENT '当前路线方案编码',
    total_deliveries INT NULL DEFAULT 0   COMMENT '总配送次数',
    total_distance  DECIMAL(10,2) NULL DEFAULT 0 COMMENT '总行驶距离(km)',
    created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_vehicle_status (status),
    INDEX idx_vehicle_code (vehicle_code),
    INDEX idx_vehicle_number (vehicle_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='车辆信息表';

CREATE TABLE IF NOT EXISTS tb_route_plan (
    id                BIGINT AUTO_INCREMENT PRIMARY KEY,
    plan_code         VARCHAR(50)  NOT NULL UNIQUE COMMENT '方案编码',
    plan_name         VARCHAR(100) NULL     COMMENT '方案名称',
    vehicle_code      VARCHAR(50)  NULL     COMMENT '关联车辆编码',
    driver_name       VARCHAR(50)  NULL     COMMENT '司机姓名',
    driver_phone      VARCHAR(20)  NULL     COMMENT '司机电话',
    status            VARCHAR(20)  NOT NULL DEFAULT 'PENDING' COMMENT '状态:PENDING,OPTIMIZING,OPTIMIZED,IN_PROGRESS,COMPLETED,CANCELLED',
    total_distance    DECIMAL(10,2) NULL    COMMENT '总距离(km)',
    estimated_duration INT NULL             COMMENT '预估时长(分钟)',
    planned_start_time DATETIME NULL        COMMENT '计划开始时间',
    planned_end_time   DATETIME NULL        COMMENT '计划结束时间',
    actual_start_time  DATETIME NULL        COMMENT '实际开始时间',
    actual_end_time    DATETIME NULL        COMMENT '实际结束时间',
    optimization_type  VARCHAR(20) NULL     COMMENT '优化类型:DISTANCE_MINIMIZE,TIME_MINIMIZE,COST_MINIMIZE,BALANCED',
    total_cost         DECIMAL(10,2) NULL   COMMENT '总成本',
    remarks           VARCHAR(500) NULL     COMMENT '备注',
    created_at        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_route_plan_status (status),
    INDEX idx_route_plan_code (plan_code),
    INDEX idx_route_plan_vehicle (vehicle_code),
    INDEX idx_route_plan_planned_start (planned_start_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='路线方案表';

CREATE TABLE IF NOT EXISTS tb_route_point (
    id                      BIGINT AUTO_INCREMENT PRIMARY KEY,
    route_plan_id           BIGINT       NULL     COMMENT '所属路线方案ID',
    point_code              VARCHAR(50)  NOT NULL UNIQUE COMMENT '点位编码',
    point_name              VARCHAR(100) NULL     COMMENT '点位名称',
    type                    VARCHAR(20)  NOT NULL COMMENT '类型:WAREHOUSE,CUSTOMER,PICKUP,DROP_OFF,SERVICE,REST',
    latitude                DECIMAL(10,6) NULL    COMMENT '纬度',
    longitude               DECIMAL(10,6) NULL    COMMENT '经度',
    address                 VARCHAR(200) NULL     COMMENT '地址',
    contact_person          VARCHAR(50)  NULL     COMMENT '联系人',
    contact_phone           VARCHAR(20)  NULL     COMMENT '联系电话',
    sequence                INT          NULL     COMMENT '排序序号',
    estimated_arrival_time  DECIMAL(10,2) NULL    COMMENT '预计到达时间(小时)',
    actual_arrival_time     DECIMAL(10,2) NULL    COMMENT '实际到达时间(小时)',
    expected_service_duration INT NULL             COMMENT '预期服务时长(分钟)',
    actual_service_duration   INT NULL             COMMENT '实际服务时长(分钟)',
    status                  VARCHAR(20)  NOT NULL DEFAULT 'PENDING' COMMENT '状态:PENDING,ARRIVED,SERVING,COMPLETED,SKIPPED,FAILED',
    distance_from_previous  DECIMAL(10,2) NULL    COMMENT '与上一站距离(km)',
    order_code              VARCHAR(50)  NULL     COMMENT '关联订单编码',
    remarks                 VARCHAR(500) NULL     COMMENT '备注',
    created_at              DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at              DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_route_point_plan (route_plan_id),
    INDEX idx_route_point_code (point_code),
    INDEX idx_route_point_status (status),
    CONSTRAINT fk_route_point_plan FOREIGN KEY (route_plan_id) REFERENCES tb_route_plan(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='路线点位表';
