server:
  port: 10112
spring:
  application:
    name: reporting-service
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:25}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:false}
          starttls:
            enable: ${MAIL_STARTTLS:false}
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-common-dev.yml
---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-common-prod.yml
