server:
  port: 10112
spring:
  application:
    name: reporting-service
  profiles:
    active: dev
  cloud:
    zookeeper:
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
        metadata:
          version: 1.0.0
        service-name: ${spring.application.name}
---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-common-dev.yml
---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-common-prod.yml
