server:
  port: 10120
spring:
  application:
    name: project-service
  profiles:
    active: dev
logging:
  level:
    com.metawebthree: debug
---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-common-dev.yml
---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-common-prod.yml