// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: web3/token.proto
// Protobuf Java Version: 4.32.0

package web3;

@com.google.protobuf.Generated
public interface TokenOrBuilder extends
    // @@protoc_insertion_point(interface_extends:web3.Token)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>string amount = 2;</code>
   * @return The amount.
   */
  java.lang.String getAmount();
  /**
   * <code>string amount = 2;</code>
   * @return The bytes for amount.
   */
  com.google.protobuf.ByteString
      getAmountBytes();

  /**
   * <code>uint32 decimals = 3;</code>
   * @return The decimals.
   */
  int getDecimals();
}
