-- 供应商绩效评估表
CREATE TABLE IF NOT EXISTS `supplier_performance` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `supplier_id` BIGINT NOT NULL COMMENT '供应商ID',
  `supplier_code` VARCHAR(50) COMMENT '供应商编码',
  `supplier_name` VARCHAR(200) COMMENT '供应商名称',
  `period_start` DATE NOT NULL COMMENT '评估周期开始日期',
  `period_end` DATE NOT NULL COMMENT '评估周期结束日期',
  `on_time_delivery_rate` DECIMAL(5,2) COMMENT '交货及时率 (0-100)',
  `quality_pass_rate` DECIMAL(5,2) COMMENT '质量合格率 (0-100)',
  `price_competitiveness_score` DECIMAL(5,2) COMMENT '价格竞争力评分 (0-100)',
  `overall_score` DECIMAL(5,2) COMMENT '综合评分 (0-100)',
  `assessment_level` VARCHAR(10) COMMENT '评估等级 (A/B/C/D)',
  `total_orders` INT COMMENT '订单总数',
  `on_time_delivery_count` INT COMMENT '准时交付订单数',
  `qualified_count` INT COMMENT '质检合格数量',
  `total_quality_check_count` INT COMMENT '质检总数量',
  `market_avg_price` DECIMAL(18,2) COMMENT '市场平均价格',
  `supplier_price` DECIMAL(18,2) COMMENT '供应商价格',
  `remark` VARCHAR(500) COMMENT '备注',
  `assessor` VARCHAR(100) COMMENT '评估人',
  `assessment_date` DATETIME COMMENT '评估时间',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  INDEX `idx_supplier_id` (`supplier_id`),
  INDEX `idx_period` (`period_start`, `period_end`),
  INDEX `idx_assessment_level` (`assessment_level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='供应商绩效评估表';