apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service
  namespace: meta-web-three
  labels:
    app: message-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: message-service
  template:
    metadata:
      labels:
        app: message-service
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z mysql-service 3306; do echo waiting for mysql; sleep 2; done;']
      - name: wait-for-redis
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z redis-service 6379; do echo waiting for redis; sleep 2; done;']
      - name: wait-for-zookeeper
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z zookeeper-service 2181; do echo waiting for zookeeper; sleep 2; done;']
      containers:
      - name: message-service
        image: meta-web-three/message-service:latest
        ports:
        - containerPort: 10085
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SERVER_PORT
          value: "10085"
        volumeMounts:
        - name: app-config
          mountPath: /app/config
        - name: message-data
          mountPath: /server/message
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 10085
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 10085
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: app-config
        configMap:
          name: app-config
      - name: message-data
        persistentVolumeClaim:
          claimName: message-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: message-data-pvc
  namespace: meta-web-three
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: message-service
  namespace: meta-web-three
  labels:
    app: message-service
spec:
  selector:
    app: message-service
  ports:
  - port: 10085
    targetPort: 10085
  type: ClusterIP 