-- Project Management Module Database Schema

-- Project Table
CREATE TABLE IF NOT EXISTS pm_project (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    project_code VARCHAR(50) NOT NULL UNIQUE COMMENT 'Project Code',
    project_name VARCHAR(200) NOT NULL COMMENT 'Project Name',
    description TEXT COMMENT 'Description',
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' COMMENT 'Status: DRAFT, ACTIVE, SUSPENDED, COMPLETED, CANCELLED',
    department_id BIGINT COMMENT 'Department ID',
    department_name VARCHAR(100) COMMENT 'Department Name',
    manager_id BIGINT COMMENT 'Manager ID',
    manager_name VARCHAR(50) COMMENT 'Manager Name',
    start_date DATE COMMENT 'Start Date',
    end_date DATE COMMENT 'End Date',
    budget_amount DECIMAL(15, 2) DEFAULT 0 COMMENT 'Budget Amount',
    used_amount DECIMAL(15, 2) DEFAULT 0 COMMENT 'Used Amount',
    currency VARCHAR(10) DEFAULT 'CNY' COMMENT 'Currency',
    progress INT DEFAULT 0 COMMENT 'Progress 0-100',
    created_by BIGINT NOT NULL COMMENT 'Creator ID',
    creator_name VARCHAR(50) NOT NULL COMMENT 'Creator Name',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
    updated_by BIGINT COMMENT 'Updater ID',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
    remark VARCHAR(500) COMMENT 'Remark',
    INDEX idx_project_code (project_code),
    INDEX idx_status (status),
    INDEX idx_department (department_id),
    INDEX idx_manager (manager_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Project Table';

-- Task Table
CREATE TABLE IF NOT EXISTS pm_task (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    project_id BIGINT NOT NULL COMMENT 'Project ID',
    task_code VARCHAR(50) NOT NULL UNIQUE COMMENT 'Task Code',
    task_name VARCHAR(200) NOT NULL COMMENT 'Task Name',
    description TEXT COMMENT 'Description',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'Status: PENDING, IN_PROGRESS, COMPLETED, CANCELLED',
    parent_id BIGINT COMMENT 'Parent Task ID',
    level INT DEFAULT 1 COMMENT 'Task Level',
    sort INT DEFAULT 0 COMMENT 'Sort Order',
    assignee_id BIGINT COMMENT 'Assignee ID',
    assignee_name VARCHAR(50) COMMENT 'Assignee Name',
    planned_start_date DATETIME COMMENT 'Planned Start Date',
    planned_end_date DATETIME COMMENT 'Planned End Date',
    actual_start_date DATETIME COMMENT 'Actual Start Date',
    actual_end_date DATETIME COMMENT 'Actual End Date',
    progress INT DEFAULT 0 COMMENT 'Progress 0-100',
    estimated_hours INT DEFAULT 0 COMMENT 'Estimated Hours',
    actual_hours INT DEFAULT 0 COMMENT 'Actual Hours',
    created_by BIGINT NOT NULL COMMENT 'Creator ID',
    creator_name VARCHAR(50) NOT NULL COMMENT 'Creator Name',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
    updated_by BIGINT COMMENT 'Updater ID',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
    remark VARCHAR(500) COMMENT 'Remark',
    INDEX idx_project (project_id),
    INDEX idx_parent (parent_id),
    INDEX idx_status (status),
    INDEX idx_assignee (assignee_id),
    FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Task Table';

-- Time Entry Table
CREATE TABLE IF NOT EXISTS pm_time_entry (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    project_id BIGINT NOT NULL COMMENT 'Project ID',
    project_name VARCHAR(200) COMMENT 'Project Name',
    task_id BIGINT COMMENT 'Task ID',
    task_name VARCHAR(200) COMMENT 'Task Name',
    employee_id BIGINT NOT NULL COMMENT 'Employee ID',
    employee_name VARCHAR(50) NOT NULL COMMENT 'Employee Name',
    work_date DATE NOT NULL COMMENT 'Work Date',
    hours DECIMAL(5, 2) NOT NULL COMMENT 'Hours',
    work_type VARCHAR(50) COMMENT 'Work Type: DEVELOPMENT, TESTING, MEETING, RESEARCH, OTHER',
    description VARCHAR(500) COMMENT 'Description',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'Status: PENDING, APPROVED, REJECTED',
    approver_id BIGINT COMMENT 'Approver ID',
    approver_name VARCHAR(50) COMMENT 'Approver Name',
    approved_at DATETIME COMMENT 'Approved At',
    created_by BIGINT NOT NULL COMMENT 'Creator ID',
    creator_name VARCHAR(50) NOT NULL COMMENT 'Creator Name',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
    updated_by BIGINT COMMENT 'Updater ID',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
    remark VARCHAR(500) COMMENT 'Remark',
    INDEX idx_project (project_id),
    INDEX idx_task (task_id),
    INDEX idx_employee (employee_id),
    INDEX idx_work_date (work_date),
    INDEX idx_status (status),
    FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE CASCADE,
    FOREIGN KEY (task_id) REFERENCES pm_task(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Time Entry Table';

-- Cost Record Table
CREATE TABLE IF NOT EXISTS pm_cost_record (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    project_id BIGINT NOT NULL COMMENT 'Project ID',
    project_name VARCHAR(200) COMMENT 'Project Name',
    cost_type VARCHAR(50) NOT NULL COMMENT 'Cost Type: LABOR, MATERIAL, EQUIPMENT, OTHER',
    cost_code VARCHAR(50) COMMENT 'Cost Code',
    cost_name VARCHAR(200) NOT NULL COMMENT 'Cost Name',
    amount DECIMAL(15, 2) NOT NULL COMMENT 'Amount',
    currency VARCHAR(10) DEFAULT 'CNY' COMMENT 'Currency',
    cost_date DATE NOT NULL COMMENT 'Cost Date',
    description VARCHAR(500) COMMENT 'Description',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'Status: PENDING, APPROVED, REJECTED',
    department_id BIGINT COMMENT 'Department ID',
    department_name VARCHAR(100) COMMENT 'Department Name',
    created_by BIGINT NOT NULL COMMENT 'Creator ID',
    creator_name VARCHAR(50) NOT NULL COMMENT 'Creator Name',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
    updated_by BIGINT COMMENT 'Updater ID',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
    remark VARCHAR(500) COMMENT 'Remark',
    INDEX idx_project (project_id),
    INDEX idx_cost_type (cost_type),
    INDEX idx_cost_date (cost_date),
    INDEX idx_status (status),
    INDEX idx_department (department_id),
    FOREIGN KEY (project_id) REFERENCES pm_project(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Cost Record Table';