server:
  port: 10097

spring:
  application:
    name: review-service
  config:
    import:
      - optional:classpath:application-common.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meta_web_three?useUnicode=true&amp;characterEncoding=utf8&amp;serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.metawebthree.review.domain.model

dubbo:
  protocol:
    name: dubbo
    port: 20887