server:
  port: 10097
spring:
  application:
    name: review-service
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.metawebthree.review.domain.model
dubbo:
  protocol:
    name: dubbo
    port: 20887
---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-common-dev.yml
---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - optional:classpath:application-common.yml
      - optional:classpath:application-common-prod.yml