from typing import Protocol, Dict, Any

class BinningService(Protocol):
    def generate(self, df: Any, target: str) -> Any: ...
    def apply(self, df: Any, bins: Any) -> Any: ...

class ModelStore(Protocol):
    def load(self) -> Dict[str, Any]: ...
    def save(self, payload: Dict[str, Any]) -> None: ...

class PredictionModel(Protocol):
    def predict_proba(self, X: Any) -> Any: ...

